<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQR9LFoQ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQR9LFoQ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQR9LFoQ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQR9LFoQ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQR9LFoQ\App_KernelProdContainer([
    'container.build_hash' => 'QR9LFoQ',
    'container.build_id' => 'b061537d',
    'container.build_time' => 1621084882,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQR9LFoQ');
