<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9XXsbRk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9XXsbRk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9XXsbRk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9XXsbRk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9XXsbRk\App_KernelDevDebugContainer([
    'container.build_hash' => '9XXsbRk',
    'container.build_id' => 'acf29d0b',
    'container.build_time' => 1621084379,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9XXsbRk');
